### ISSUE TITLE
Android开发

### ISSUE THREAD

**Issue by hushicai** [hushicai/hushicai.github.io#70]
本人在工作过程中主要以react native为技术栈，偶尔会涉及到一些Android端开发，特在本issue中记录一些Android开发知识点。

**Comment by hushicai** [comment]
## gradle buildscript与allprojects

`buildscript`主要用于gradle本身，例如gradle plugin。

`allprojects`主要用于gradle构建的项目。

**Comment by hushicai** [comment]
## gradle依赖管理

## 公共仓库

gradle内置了一些常用的公共仓库：

![image](https://user-images.githubusercontent.com/1249423/66820861-058ecc00-ef74-11e9-9571-b34622215dc1.png)

例如使用`jcenter`：

```groovy
repositories {
    jcenter()
}
```

## 自定义仓库

```groovy
repositories {
    maven {
      url 'http://repo.mycompany.com/maven2'
    }
}
```

**Comment by hushicai** [comment]
Android Studio无法下载distributionUrl问题 #46

**Comment by hushicai** [comment]
## 阿里云镜像

https://maven.aliyun.com/mvn/view

**Comment by hushicai** [comment]
## gradle代理

gradle不走`proxyHost`，正确的姿势应该是在`$HOME/.gradle/gradle.properties`中添加以下配置：

```
org.gradle.jvmargs=-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1086
```

**Comment by hushicai** [comment]
[Android Support Library的前世今生](https://www.jianshu.com/p/f5f9a4fd22e8)

**Comment by hushicai** [comment]
[如何选择 compileSdkVersion, minSdkVersion 和 targetSdkVersion](https://chinagdg.org/2016/01/picking-your-compilesdkversion-minsdkversion-targetsdkversion/)

**Comment by hushicai** [comment]
## ABI

[Gradle的ABI](https://www.jianshu.com/p/86c4397d296c)

[针对 ABI 配置多个 APK](https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split)

[NDK ABI管理](https://developer.android.com/ndk/guides/abis)

**Comment by hushicai** [comment]
[介绍Android O新的"安装未知应用"权限](https://juejin.im/entry/59a505946fb9a0247e426c57)

实践中发现只要添加了以下权限，即可解决应用自更新问题：

```xml
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
```

**Comment by hushicai** [comment]
## react native android 64位支持

国内部分5.0机型不支持带64位so，当apk中包含64位时，就会导致启动失败。

```
#4685	11-05 18:21:44.059	7529	E	AndroidRuntime	 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libfb.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/<package>/lib-main/libc++_shared.so" is 64-bit instead of 32-bit
#4686	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
#4687	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
#4688	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
#4689	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
#4690	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
#4691	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.react.bridge.NativeMap.(NativeMap.java:19)
#4692	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
#4693	11-05 18:21:44.059	7529	E	AndroidRuntime	         at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
#4694	11-05 18:21:44.059	7529	E	AndroidRuntime	         at java.lang.Thread.run(Thread.java:818)
```

在 facebook/react-native#23764 提到了一种`pickFirst`解决方案，不过没用，这是部分厂商ROM的问题。

目前国内厂商还没有限制64位，暂时先不要带64位so吧！

**Comment by hushicai** [comment]
## android 下报错 AAPT: error: resource android:attr/fontVariationSettings not found

具体报错的插件为`react-native-reanimated`，查了一番，发现是targetSdk版本不一致导致的。

我们主项目的targetSdk为26，`react-native-reanimated@^1.3.0`默认的targetSdk为28，过高了，所以assembleRelease失败。

降级到`react-native-reanimated@^1.0.1`解决了问题。
